project:
  type: website
  output-dir: docs
  render:
    - index.qmd
      
website:
  title: ""

  navbar:
    background: "#00205B"
    search: true
    left:

      - text: "Home"
        file: index.qmd

     
format: 
  html:
    theme: cyborg
    scss: styles.css
   



