project:
  type: website
  output-dir: docs
  render:
    - index.qmd
           
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: BUSI 520
    right:

      - text: Code Binder
        href: https://mybinder.org/v2/gh/kerryback/2022-520-binder.git/HEAD
        
    theme: cosmo
    scss: styles.css
   



